# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='model.masks',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btypes.proto\x12\x0bmodel.masks\"^\n\x04\x42\x42ox\x12\x12\n\ntop_left_x\x18\x01 \x01(\x02\x12\x12\n\ntop_left_y\x18\x02 \x01(\x02\x12\x16\n\x0e\x62ottom_right_x\x18\x03 \x01(\x02\x12\x16\n\x0e\x62ottom_right_y\x18\x04 \x01(\x02\"h\n\x0fObjectDetection\x12\x1f\n\x04\x62\x62ox\x18\x01 \x01(\x0b\x32\x11.model.masks.BBox\x12\x11\n\tcoco_mask\x18\x02 \x01(\x0c\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x12\n\npred_class\x18\x04 \x01(\x05\"\\\n\x15\x46rameObjectDetections\x12\x14\n\x0c\x66rame_number\x18\x02 \x01(\x05\x12-\n\x07objects\x18\x03 \x03(\x0b\x32\x1c.model.masks.ObjectDetectionb\x06proto3'
)




_BBOX = _descriptor.Descriptor(
  name='BBox',
  full_name='model.masks.BBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_left_x', full_name='model.masks.BBox.top_left_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_left_y', full_name='model.masks.BBox.top_left_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom_right_x', full_name='model.masks.BBox.bottom_right_x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom_right_y', full_name='model.masks.BBox.bottom_right_y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=122,
)


_OBJECTDETECTION = _descriptor.Descriptor(
  name='ObjectDetection',
  full_name='model.masks.ObjectDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bbox', full_name='model.masks.ObjectDetection.bbox', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coco_mask', full_name='model.masks.ObjectDetection.coco_mask', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='model.masks.ObjectDetection.score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pred_class', full_name='model.masks.ObjectDetection.pred_class', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=228,
)


_FRAMEOBJECTDETECTIONS = _descriptor.Descriptor(
  name='FrameObjectDetections',
  full_name='model.masks.FrameObjectDetections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_number', full_name='model.masks.FrameObjectDetections.frame_number', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objects', full_name='model.masks.FrameObjectDetections.objects', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=322,
)

_OBJECTDETECTION.fields_by_name['bbox'].message_type = _BBOX
_FRAMEOBJECTDETECTIONS.fields_by_name['objects'].message_type = _OBJECTDETECTION
DESCRIPTOR.message_types_by_name['BBox'] = _BBOX
DESCRIPTOR.message_types_by_name['ObjectDetection'] = _OBJECTDETECTION
DESCRIPTOR.message_types_by_name['FrameObjectDetections'] = _FRAMEOBJECTDETECTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BBox = _reflection.GeneratedProtocolMessageType('BBox', (_message.Message,), {
  'DESCRIPTOR' : _BBOX,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:model.masks.BBox)
  })
_sym_db.RegisterMessage(BBox)

ObjectDetection = _reflection.GeneratedProtocolMessageType('ObjectDetection', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDETECTION,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:model.masks.ObjectDetection)
  })
_sym_db.RegisterMessage(ObjectDetection)

FrameObjectDetections = _reflection.GeneratedProtocolMessageType('FrameObjectDetections', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEOBJECTDETECTIONS,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:model.masks.FrameObjectDetections)
  })
_sym_db.RegisterMessage(FrameObjectDetections)


# @@protoc_insertion_point(module_scope)
